name = "rush-pos"
main = "server.js"
compatibility_date = "2026-09-22"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "rush-pos-db"
database_id = "79ed43c7-40b8-4a8a-bec5-1fd69449774b"
migrations_dir = "migrations"
