name = "rush-pos"
main = "server.js"
compatibility_date = "2026-03-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "rush-pos-db"
database_id = "tu-id-de-base-de-datos"
